### ISSUE TITLE
For Translation

### ISSUE THREAD

**Issue by alhitary** [AlfredoRamos/phpbb-ext-auto-lock-topics#1]
Dear,

I need the clarification for the bellow 2 things to be able to translate very well.

The line :

`	'ACP_AUTO_LOCK_POLLS_EXPLAIN'	=> 'Locks topics with polls not voted in fo post age days.',
`

Is it Ok ? no mistake with "fo" ?

Also, I need more explain to the bellow line :

`	'ACP_AUTO_LOCK_FREQ'		=> 'Auto-lock frequency',`
`	'ACP_AUTO_LOCK_FREQ_EXPLAIN' => 'Time in days between auto-lock events.',`

I couldn't understand what is the frequency or events

Thanks

**Comment by AlfredoRamos** [comment]
Yes `ACP_AUTO_LOCK_POLLS_EXPLAIN` has a typo, I've fixed it.

- `ACP_AUTO_LOCK_POLLS_EXPLAIN` If a topic have a poll, it will check the date of last vote instead of the date of last post.
- `ACP_AUTO_LOCK_FREQ` Cron will wait this number of days to run the task again.
- `ACP_AUTO_LOCK_FREQ_EXPLAIN` It just adds a little explanation about the above.

Frequency means, just as in statistics, the amount of times that it will run during the execution. For example, if you set `1` the cron task will run daily, if you set `7` it will run weekly, and so on.

Event is used as synonym of activity or, in this case, a cron task.

Thanks in advance for your contribution.

**Comment by alhitary** [comment]
Thanks alot.
PR for Arabic Language : https://github.com/AlfredoRamos/phpbb-ext-auto-lock-topics/pull/2

**Comment by AlfredoRamos** [comment]
Merged, thank you.
