### ISSUE TITLE
auto_lock_topics task does not appear in phpbbcli.php cron:list

### ISSUE THREAD

**Issue by mudge** [AlfredoRamos/phpbb-ext-auto-lock-topics#13]
As we have hundreds of thousands of topics in our phpBB install, I'm attempting to switch to using [phpBB's "Run periodic tasks from system cron"](https://wiki.phpbb.com/PhpBB3.1/RFC/Modular_cron#Use_system_cron) but the Auto-lock Topics extension's task doesn't appear in the list of available cron tasks when using phpBB 3.3.3 and PHP 7.3.27-1~deb10u1:

```console
$ php bin/phpbbcli.php cron:list


Ready tasks:
============

 * cron.task.core.tidy_cache
 * cron.task.core.tidy_sessions
 * cron.task.core.tidy_warnings

Not ready tasks:
================

 * cron.task.core.prune_all_forums
 * cron.task.core.prune_forum
 * cron.task.core.prune_shadow_topics
 * cron.task.core.prune_notifications
 * cron.task.core.queue
 * cron.task.core.tidy_database
 * cron.task.core.tidy_plupload
 * cron.task.core.tidy_search
 * cron.task.text_reparser.pm_text
 * cron.task.text_reparser.poll_option
 * cron.task.text_reparser.poll_title
 * cron.task.text_reparser.post_text
 * cron.task.text_reparser.user_signature
 * cron.task.core.update_hashes
```

I tried adding `is_runnable` and `should_run` methods to the cron task but to no avail.

Is it possible to support running the task from the CLI or does it only work if executed via a request?

**Comment by AlfredoRamos** [comment]
Hi @mudge  :wave: 

> I'm attempting to switch to using phpBB's "Run periodic tasks from system cron" but the Auto-lock Topics extension's task doesn't appear in the list of available cron tasks

Yes, It's a known bug of phpBB.

https://tracker.phpbb.com/browse/PHPBB3-16591

It worked before, because that's how I debugged this extension when I started developing it, however at some point a new phpBB version broke it.

> I tried adding `is_runnable` and `should_run` methods to the cron task but to no avail.

Yes, it already inherits from the base task class where both methods return `true` it won't make a difference.

> Is it possible to support running the task from the CLI or does it only work if executed via a request?

Well, as I said, it's not really a bug of this extension but from phpBB itself.

So unless they fix it, which unfortunately I don't believe it will be anytime soon, the only way to run using the CLI would be to send HTTP request like `curl`, something like:

```shell
curl -kIL "https://{DOMAIN}/app.php/cron/cron.task.auto_lock_topics"
```

However your task would need to be running in intervals of more than 1 hour, since that's a phpBB [hard-coded value](https://github.com/phpbb/phpbb/blob/7d48254cc9160690e30d41ba2e27cfb06d47ccbb/phpBB/phpbb/controller/helper.php#L352) to wait until the cron is unlocked, unless you remove the cron lock manually before running the task, which could potentially break other cron tasks.

```sql
UPDATE phpbb_config SET config_value = 0 WHERE config_name = 'cron_lock' and config_value <> 0;
```

**Comment by mudge** [comment]
Hi @AlfredoRamos,

Thanks so much for the prompt and thorough response.

As this is outside of your control, I’ll close this issue and rely on the default non-system cron for now (hitting the app.php/cron/ endpoint if I need to force a run).
